# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='FechaAlquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_que_se_puede_alquilar', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'fechaAlquileres',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Huespedes',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_diario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('numero_ficha', models.IntegerField()),
                ('max_pax', models.IntegerField()),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobiliaria.Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobiliaria.Reserva'),
        ),
        migrations.AddField(
            model_name='fechaalquiler',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobiliaria.Propiedad'),
        ),
        migrations.AddField(
            model_name='fechaalquiler',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inmobiliaria.Reserva'),
        ),
    ]
